// Generated by CoffeeScript 1.4.0
(function() {

  this.Wraith.Bootloader = (function() {

    function Bootloader() {
      var $controller, controller, controllers, id, _i, _len, _ref;
      controllers = document.querySelectorAll('[data-controller]');
      for (_i = 0, _len = controllers.length; _i < _len; _i++) {
        $controller = controllers[_i];
        this.loadController($controller.attributes['data-controller'].value, $controller);
      }
      _ref = Wraith.controllers;
      for (id in _ref) {
        controller = _ref[id];
        controller.init();
      }
      this;

    }

    Bootloader.prototype.loadController = function(id, $item) {
      var Controller, controller;
      if (!(Controller = Wraith.Controllers[id])) {
        throw 'Controller does not exist';
      }
      controller = new Controller($item);
      return Wraith.controllers[controller.id] = controller;
    };

    return Bootloader;

  })();

}).call(this);
