// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Wraith.CollectionView = (function(_super) {

    __extends(CollectionView, _super);

    function CollectionView($el, template) {
      this.$el = $el;
      this.template = template;
      if (Wraith.DEBUG) {
        console.log('@Wraith.CollectionView', 'constructor');
      }
      CollectionView.__super__.constructor.call(this, this.$el, this.template);
      this.$parent.innerHTML = '';
    }

    CollectionView.prototype.createView = function(model) {
      var $el, $node;
      if (!(model instanceof Wraith.Model)) {
        return;
      }
      $el = this.render(model);
      if (!($node = $el)) {
        return;
      }
      $node.setAttribute('data-id', Wraith.uniqueId());
      $node.setAttribute('data-model', model.get('_id'));
      this.$parent.appendChild($el);
      return this.bindEvents($el);
    };

    CollectionView.prototype.removeView = function(model) {
      var $el;
      if (!(model instanceof Wraith.Model)) {
        return;
      }
      $el = this.$parent.querySelector('[data-model=' + model.get('_id') + ']');
      return this.$parent.removeChild($el);
    };

    CollectionView.prototype.updateView = function(model) {
      var $el, $node, $oldView;
      if (!($oldView = this.$parent.querySelector('[data-model=' + model.get('_id') + ']'))) {
        return;
      }
      $el = this.render(model);
      if (!($node = $el)) {
        return;
      }
      $node.setAttribute('data-id', Wraith.uniqueId());
      $node.setAttribute('data-model', model.get('_id'));
      this.$parent.replaceChild($node, $oldView);
      return this.bindEvents($node);
    };

    return CollectionView;

  })(this.Wraith.ViewModel);

}).call(this);
