// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Wraith.Model = (function(_super) {

    __extends(Model, _super);

    Model.field = function(name, opt) {
      var _ref;
      if ((_ref = this.fields) == null) {
        this.fields = {};
      }
      return this.fields[name] = opt != null ? opt : {};
    };

    Model.hasMany = function(klass, opt) {
      var _ref, _ref1;
      if (opt == null) {
        opt = {};
      }
      if ((_ref = opt.klass) == null) {
        opt.klass = klass;
      }
      if ((_ref1 = this.collections) == null) {
        this.collections = {};
      }
      return this.collections[opt.as] = opt;
    };

    function Model(attributes) {
      this.toJSON = __bind(this.toJSON, this);

      this.set = __bind(this.set, this);

      this.get = __bind(this.get, this);

      var d, name, options, _base, _ref, _ref1, _ref2;
      Model.__super__.constructor.call(this);
      if ((_ref = (_base = this.constructor).fields) == null) {
        _base.fields = {};
      }
      if (!(attributes != null ? attributes['_id'] : void 0)) {
        this.constructor.fields['_id'] = {
          "default": Wraith.uniqueId
        };
      }
      this.listeners = {};
      this.attributes = {};
      _ref1 = this.constructor.fields;
      for (name in _ref1) {
        options = _ref1[name];
        if ((attributes != null ? attributes[name] : void 0) != null) {
          d = attributes != null ? attributes[name] : void 0;
        } else {
          d = Wraith.isFunction(options["default"]) ? options["default"]() : options["default"];
        }
        this.set(name, d);
      }
      _ref2 = this.constructor.collections;
      for (name in _ref2) {
        options = _ref2[name];
        this.attributes[name] = new Wraith.Collection(this, options.as, options.klass);
      }
      Wraith.models[this.attributes['_id']] = this;
      this;

    }

    Model.prototype.get = function(key) {
      var _ref;
      return (_ref = this.attributes) != null ? _ref[key] : void 0;
    };

    Model.prototype.set = function(key, val) {
      var field;
      if (!(field = this.constructor.fields[key])) {
        throw 'Trying to set an non-existent property!';
      }
      if (val === this.get(key)) {
        return;
      }
      this.attributes[key] = val;
      this.emit('change', key, val);
      return this.emit("change:" + key, val);
    };

    Model.prototype.toJSON = function() {
      return this.attributes;
    };

    return Model;

  })(this.Wraith.Base);

}).call(this);
