// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Models = {};

  this.Controllers = {};

  this.Views = {};

  this.Models.Test = (function(_super) {

    __extends(Test, _super);

    function Test() {
      return Test.__super__.constructor.apply(this, arguments);
    }

    Test.field('someData');

    return Test;

  })(Wraith.Model);

  this.Controllers.Test = (function(_super) {

    __extends(Test, _super);

    function Test() {
      return Test.__super__.constructor.apply(this, arguments);
    }

    return Test;

  })(Wraith.Controller);

}).call(this);
