// Generated by CoffeeScript 1.6.3
(function() {
  var App, root, _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.App = App = {};

  App.ListItem = (function(_super) {
    __extends(ListItem, _super);

    function ListItem() {
      _ref = ListItem.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ListItem.field('text', {
      "default": ''
    });

    ListItem.field('selected', {
      "default": false
    });

    return ListItem;

  })(Wraith.Model);

  App.List = (function(_super) {
    __extends(List, _super);

    function List() {
      this.completed = __bind(this.completed, this);
      _ref1 = List.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    List.hasMany(App.ListItem, 'items');

    List.prototype.completed = function() {
      var items;
      items = this.get('items').all();
      items = items.filter(function(item) {
        return item.get('selected') === true;
      });
      return items.length;
    };

    return List;

  })(Wraith.Model);

  App.TodoManager = (function(_super) {
    __extends(TodoManager, _super);

    function TodoManager() {
      this.itemToggle = __bind(this.itemToggle, this);
      this.itemDelete = __bind(this.itemDelete, this);
      _ref2 = TodoManager.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    TodoManager.prototype.init = function() {
      TodoManager.__super__.init.call(this);
      this.list = this.registerModel(new App.List, 'list');
      this.items = this.list.get('items');
      this.items.create({
        text: 'Task 1',
        selected: true
      });
      this.items.create({
        text: 'Task 2'
      });
      return this.items.create({
        text: 'Task 3'
      });
    };

    TodoManager.prototype.itemDelete = function(e) {
      return this.items.remove(e.model.get('_id'));
    };

    TodoManager.prototype.itemToggle = function(e) {
      return e.model.set('selected', !e.model.get('selected'));
    };

    return TodoManager;

  })(Wraith.Controller);

}).call(this);
