// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  describe("Model", function() {
    var TestModel, model, _ref;
    model = null;
    TestModel = (function(_super) {
      __extends(TestModel, _super);

      function TestModel() {
        _ref = TestModel.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      TestModel.field("a", {
        "default": false
      });

      TestModel.field("b", {
        "default": true
      });

      return TestModel;

    })(Wraith.Model);
    beforeEach(function() {
      return model = new TestModel();
    });
    it("should have get and set functions", function() {
      expect(model.get).toBeFunction();
      return expect(model.set).toBeFunction();
    });
    describe("on creation", function() {
      it("should have getters for each field", function() {
        expect(model.get('a')).toExist();
        return expect(model.get('b')).toExist();
      });
      it("should have defaults for each field", function() {
        expect(model.get('a')).toBe(false);
        return expect(model.get('b')).toBe(true);
      });
      return it("should be initialized with custom data", function() {
        var model_;
        model_ = new TestModel({
          a: true,
          b: false
        });
        expect(model_.get('a')).toBe(true);
        return expect(model_.get('b')).toBe(false);
      });
    });
    describe("on set", function() {
      it("should update the field to the desired value", function() {
        expect(model.get('a')).toBe(false);
        model.set('a', true);
        return expect(model.get('a')).toBe(true);
      });
      it("should emit a generic change event", function() {
        var val;
        val = false;
        model.bind('change', function() {
          return val = true;
        });
        model.set('a', true);
        return waitsFor((function() {
          return val === true;
        }), 100);
      });
      return it("should emit an explicit event", function() {
        var val;
        val = false;
        model.bind('change:a', function() {
          return val = true;
        });
        model.set('a', true);
        return waitsFor((function() {
          return val === true;
        }), 100);
      });
    });
    return describe("on reset", function() {
      return it("should reset all properties", function() {
        model.reset();
        expect(model.get('a')).toBe(false);
        return expect(model.get('b')).toBe(true);
      });
    });
  });

}).call(this);
