// Generated by CoffeeScript 1.6.2
(function() {
  beforeEach(function() {
    return this.addMatchers({
      toBeFunction: function() {
        return typeof this.actual === 'function';
      },
      toExist: function() {
        return this.actual !== null;
      }
    });
  });

}).call(this);
