// Generated by CoffeeScript 1.4.0
(function() {
  var root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Wraith.Models.ListItem = (function(_super) {

    __extends(ListItem, _super);

    function ListItem() {
      return ListItem.__super__.constructor.apply(this, arguments);
    }

    ListItem.field('text', {
      "default": 'New Item'
    });

    ListItem.field('selected', {
      "default": false
    });

    return ListItem;

  })(Wraith.Model);

  Wraith.Models.List = (function(_super) {

    __extends(List, _super);

    function List() {
      return List.__super__.constructor.apply(this, arguments);
    }

    List.hasMany(Wraith.Models.ListItem, {
      as: 'items'
    });

    return List;

  })(Wraith.Model);

  Wraith.Controllers.SelectList = (function(_super) {

    __extends(SelectList, _super);

    function SelectList() {
      this.keypress = __bind(this.keypress, this);
      return SelectList.__super__.constructor.apply(this, arguments);
    }

    SelectList.prototype.view = 'ListItem';

    SelectList.prototype.init = function() {
      var items;
      SelectList.__super__.init.call(this);
      this.list = new Wraith.Models.List;
      this.list.bind('add:items', this.add);
      this.list.bind('remove:items', this.remove);
      items = this.list.items;
      items.create({
        text: 'Task 1',
        selected: true
      });
      items.create({
        text: 'Task 2',
        selected: false
      });
      items.create({
        text: 'Task 3',
        selected: false
      });
      return this.bind('ui:keypress:input[type=text]', this.keypress);
    };

    SelectList.prototype.keypress = function(e) {
      var val;
      if (e.keyCode !== 13) {
        return;
      }
      if ((val = e.currentTarget.value) === '') {
        return;
      }
      this.list.items.create({
        text: val,
        selected: false
      });
      return e.currentTarget.value = '';
    };

    return SelectList;

  })(Wraith.Controller);

}).call(this);
